### PR TITLE
fix: update rxjs version to 7.5.2

### PR DESCRIPTION
**Pull request by VincentPuget**
fix some npm vulnerabilities

### CODE REVIEW

**Comment by Vincent-CHARLANNE** [comment]
+1

**Comment by HeloOwWeb** [comment]
When will the vulnerabilities be fixed?

**Comment by gloaec** [comment]
+1

**Comment by ikkdotim** [comment]
+1

**Comment by Enngage** [comment]
+1

**Review by ikkdotim — APPROVED** [review]

**Comment by CMeyer19** [comment]
+1

**Pull request closed without merging**
